name: Hostapd
version: "0.1"
slug: hostapd
description: >-
  Wi-Fi access point
arch:
  - armv7
options:
  ssid2: "ChangeMe"
  password2: "ChangeMeToo"
  channel2: "5"
  width2: "20"
  ssid5: "ChangeMe"
  password5: "ChangeMeToo"
  channel5: "161"
  width5: "80"
  interface: "wlan0"
  driver: "nl80211"
  hw_mode: "vht"
