naae: "OpenVPN Client"
version: "0.1.1"
slug: "openvpn_client"
description: "OpenVPN Client"
arch:
  - "aarch64"
  - "amd64"
  - "armhf"
  - "armv7"
  - "i386"
startup: "services"
boot: "auto"
auto_update: true
options:
  remote: ""
  port: 1194
  protocol: "udp"
  dev: "tap"
  route_delay: 10
  resolv_retry: "infinite"
  nobind: true
  persist_key: true
  persist_tun: true
  verb: 1
  comp_lzo: true
  ca_crt: "/ssl/kina-mpo_openvpn-client/ca.crt"
  client_crt: "/ssl/kina-mpo_openvpn-client/client.crt"
  client_key: "/ssl/kina-mpo_openvpn-client/client.key"
  remote_cert_tls: "server"
  auth: "SHA512"
  tls_cipher: "TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-128-GCM-SHA256:TLS-DHE-RSA-WITH-AES-256-CBC-SHA:TLS-DHE-RSA-WITH-CAMELLIA-256-CBC-SHA:TLS-DHE-RSA-WITH-AES-128-CBC-SHA:TLS-DHE-RSA-WITH-CAMELLIA-128-CBC-SHA"
  username: ""
  password: ""
schema:
  remote: "str"
  port: "port"
  verb: "list(1|2|3|4|5)"
  username: "str"
  password: "str"
ports: {}
map:
  - type: ssl
host_network: true
